### ISSUE TITLE
Adding numeralJs library seems to affect for loop in IE

### ISSUE THREAD

**Issue by keithwoodlock** [adamwdraper/Numeral-js#131]
Hi when including this library I am seeing javascript for loops affected in IE 8 and below.

example

```
for (var i in loopableObject)
{
console.log("index: " + i + " is >> " + loopableObject[i]);
}
```

**Comment by willheger** [comment]
We've traced exactly the same problem as @davemiranda reports.

Our codebase includes framework code (code we don't controle) that iterates an Array and breaks because of the prototype change.   Furthermore, lack of support for defineProperty in IE8 means we cannot make it un-iterable.

I would like to propose using a function-style reduce a'la underscore.  There are only 5 usages of .reduce() in numeralJS, so seems a modest change.

While I understand this .reduce() is defensible as a polyfill since .reduce() is eventually supported, because of the iteration problem, some of us are unfortunately stuck and we'd very much like to use this lib.

I'll happily submit a pull if this is likely to get taken-up.
