### ISSUE TITLE
format() fails if the given number is string and a zero with zero decimals

### ISSUE THREAD

**Issue by tameraydin** [adamwdraper/Numeral-js#220]
with version **1.5.3**:

`numeral(2233.00).format("0,0")` // 2,233
`numeral("2233.00").format("0,0")` // 2,233

`numeral(50.0).format("0,0")` // 50
`numeral("50.0").format("0,0")` // 50

`numeral(0.01).format("0,0")` // 0
`numeral("0.01").format("0,0")` // 0

`numeral(0.0).format("0,0")` // 0
`numeral("0.0").format("0,0")` => TypeError: Cannot read property 'thousand' of undefined

**Comment by tameraydin** [comment]
I checked it now again, and still have the issue. 

If the cause is missing *abbreviations.thousands*, isn't supposed to give the same error for above cases?

the output of language data is as following:
```json
{"delimiters":{"thousands":".","decimal":","}}
```

**Comment by laguiz** [comment]
I got the same strange behaviour and some other strange errors. I had to fully initialise numeraljs by cloning complete content of one of the language file (in my case https://github.com/adamwdraper/Numeral-js/blob/master/languages/fr.js). 

I suspect the problem is because I was doing the initialisation of numeraljs in `$(document).ready(...)`.

May help someone else.

**Comment by adamwdraper** [comment]
fixed
