### ISSUE TITLE
The big number don't format correctly

### ISSUE THREAD

**Issue by LexaDel** [adamwdraper/Numeral-js#580]
I  need format **407520730107173.01 -> 407 520 730 107 173.01**
I use **numeral(407520730107173.01).format('0,0.00')**
and i've got this result **407 520 730 107 172.94**

**Comment by summerisgone** [comment]
It's connected to my issue, #586 
`numeral('12345678901234567890123').format()`
gives `"NaN"`

**Comment by crow7m** [comment]
was it merged? is there someone taking care of this ?

**Comment by summerisgone** [comment]
@crow7m unfortunately PR only demonstrates failing tests. Repository looks no longer maintained. I'm using [bignumber.js](https://github.com/MikeMcl/bignumber.js/)

**Comment by crow7m** [comment]
Thank you for your response, will check this out.

**Comment by heatxsink** [comment]
> @crow7m unfortunately PR only demonstrates failing tests. Repository looks no longer maintained. I'm using [bignumber.js](https://github.com/MikeMcl/bignumber.js/)

I'm also experiencing the same exact issue. Is there a work around?

**Comment by summerisgone** [comment]
No, I just switched to Big.js https://github.com/MikeMcl/big.js/

**Comment by heatxsink** [comment]
I figured it out! So ... `numeral.js` is limited by `Number`'s precision (max 15 places). That's why when you pass in `let x = new BigNumber('large number here')` into `numeral(x).format()` you get a `NaN`. I got around this by using `BigNumber.toFormat()`. Documentation here: https://mikemcl.github.io/bignumber.js/#toFor
