### ISSUE TITLE
Value changes when Multiplying with 1

### ISSUE THREAD

**Issue by master117** [adamwdraper/Numeral-js#715]
https://codesandbox.io/s/boring-varahamihira-8rlxz

**Comment by bigwhoman** [comment]
actually,this is not a problem with this library but it is a problem with the '/' or division operation . the operation itself has this problem as you can see in [this link](https://jsfiddle.net/vxr8cthm/) the problem seems internal in js and not an issue of the library(if the number is not big or doesn't have lots of floating digits the operation works fine , otherwise its broken).
